name: 发布到npm私有库
on:
  push:
    tags:
      - 'v*' # 触发条件：以 'v' 开头的标签

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check branch
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          BRANCH_NAME=$(curl --silent --show-error -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT_SHA}/branches-where-head" | jq -r '.[] | select(.name == "master") | .name')
          if [[ "$BRANCH_NAME" != "master" ]]; then
            echo "这不是主分支。正在退出..."
            exit 1
          fi
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: 安装依赖
        run: pnpm i

      - name: 检测
        run: npm run doctor

      - name: 打包
        run: npm run build

      - name: 发布
        run: |
          echo "//npm.lantao.work/:_authToken=\${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          echo "@lands:registry=http://npm.lantao.work/" >> ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
