name: 发布到npm私有库
on:
  push:
    tags:
      - 'v*' # 触发条件：以 'v' 开头的标签
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: 检测
        run: npm run doctor

      - name: 打包
        run: npm run build

      - name: 发布到私有NPM注册表
        run: |
          echo "//npm.lantao.work/:_authToken=\${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          echo "@lands:registry=http://npm.lantao.work/" >> ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
